7/24/24 - seeking to import csv files from US census, clean them up, and then merge them together. Why? To create a lovely dataframe of relevent information regarding counties in kY that are critically lacking childcare options. First, I'll start with the ChildrenCharacteristics date table from the US Census website. It is the smallest file, as there was only data in this survey for 4 out of the 28 counties within the Eastern Mountian Region.

In [1]:
import pandas as pd

In [3]:
children_characteristics = pd.read_csv("C:\\Users\\carol\\Documents_Local\\AECN_Capstone\\UScensus_data\\ChildrenCharacteristics_4counties.csv", index_col=0)

In [6]:
children_characteristics.head()

,"Boyd County, Kentucky!!Total!!Estimate","Boyd County, Kentucky!!In married-couple family household!!Estimate","Boyd County, Kentucky!!In male householder, no spouse present, family household!!Estimate","Boyd County, Kentucky!!In female householder, no spouse present, family household!!Estimate","Floyd County, Kentucky!!Total!!Estimate","Floyd County, Kentucky!!In married-couple family household!!Estimate","Floyd County, Kentucky!!In male householder, no spouse present, family household!!Estimate","Floyd County, Kentucky!!In female householder, no spouse present, family household!!Estimate","Greenup County, Kentucky!!Total!!Estimate","Greenup County, Kentucky!!In married-couple family household!!Estimate","Greenup County, Kentucky!!In male householder, no spouse present, family household!!Estimate","Greenup County, Kentucky!!In female householder, no spouse present, family household!!Estimate","Pike County, Kentucky!!Total!!Estimate","Pike County, Kentucky!!In married-couple family household!!Estimate","Pike County, Kentucky!!In male householder, no spouse present, family household!!Estimate","Pike County, Kentucky!!In female householder, no spouse present, family household!!Estimate"
Label (Grouping),,,,,,,,,,,,,,,,
Children under 18 years in households,"10,325","5,901","1,320","3,032","7,901","4,562",782,"2,486","7,684","5,398",898,"1,310","11,869","7,705",953,"3,042"
AGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Under 6 years,31.4%,34.0%,28.0%,27.9%,31.5%,31.3%,23.7%,32.9%,30.1%,32.8%,18.0%,28.3%,29.4%,26.7%,24.3%,38.3%
6 to 11 years,33.2%,33.1%,37.8%,31.0%,31.3%,26.9%,47.7%,34.8%,32.2%,33.3%,34.3%,28.5%,31.8%,32.8%,33.7%,30.6%
12 to 17 years,35.5%,32.9%,34.2%,41.1%,37.2%,41.7%,28.6%,32.3%,37.6%,33.9%,47.7%,43.2%,38.8%,40.5%,42.0%,31.1%

Successfully read in the csv file with pandas...Now I need to clean it up. ...We're gonna put a pin in that for a second. Why? Because I don't really know in what way I need to clean up the data, other than the obvious like making those column names less terrible to read. 

For now, I'm going to read in a csv file I made with Google sheets to see what it looks like in comparison.

In [5]:
eastern_mt_region = pd.read_csv("C:\\Users\\carol\\Documents_Local\\AECN_Capstone\\custom_data\\AECN_EasternMountainRegion.csv", index_col=0)
eastern_mt_region.head()

,Primary City,Population,Population Under 6,County,Median Home Value,Median Household Income,Type of Internet,Number of Registered Child Care Providers
Zipcodes,,,,,,,,
41714,NaN,NaN,NaN,Leslie,NaN,NaN,NaN,0
40808,NaN,NaN,NaN,Leslie,NaN,NaN,NaN,0
40810,NaN,NaN,NaN,Leslie,NaN,NaN,NaN,0
41723,NaN,NaN,NaN,Leslie,NaN,NaN,NaN,0
40816,NaN,NaN,NaN,Leslie,NaN,NaN,NaN,0

Okay...well now what am I doing? Lets concat and see what happens?

In [6]:
df_test = pd.concat([children_characteristics, eastern_mt_region])
print(df_test)

                                      Boyd County, Kentucky!!Total!!Estimate  \
Children under 18 years in households                                 10,325
    AGE                                                                  NaN
        Under 6 years                                                  31.4%
        6 to 11 years                                                  33.2%
        12 to 17 years                                                 35.5%
...                                                                      ...
41232                                                                    NaN
41159                                                                    NaN
41254                                                                    NaN
41264                                                                    NaN
41180                                                                    NaN

                                      Boyd County, Kentucky!!In married-couple family household!!Estimate  \
Children under 18 years in households                                              5,901
    AGE                                                                              NaN
        Under 6 years                                                              34.0%
        6 to 11 years                                                              33.1%
        12 to 17 years                                                             32.9%
...                                                                                  ...
41232                                                                                NaN
41159                                                                                NaN
41254                                                                                NaN
41264                                                                                NaN
41180                                                                                NaN

                                      Boyd County, Kentucky!!In male householder, no spouse present, family household!!Estimate  \
Children under 18 years in households                                              1,320
    AGE                                                                              NaN
        Under 6 years                                                              28.0%
        6 to 11 years                                                              37.8%
        12 to 17 years                                                             34.2%
...                                                                                  ...
41232                                                                                NaN
41159                                                                                NaN
41254                                                                                NaN
41264                                                                                NaN
41180                                                                                NaN

                                      Boyd County, Kentucky!!In female householder, no spouse present, family household!!Estimate  \
Children under 18 years in households                                              3,032
    AGE                                                                              NaN
        Under 6 years                                                              27.9%
        6 to 11 years                                                              31.0%
        12 to 17 years                                                             41.1%
...                                                                                  ...
41232                                                                                NaN
41159                                                                                NaN
41254                                                                                NaN
41264                                                                                NaN
41180                                                                                NaN

                                      Floyd County, Kentucky!!Total!!Estimate  \
Children under 18 years in households                                   7,901
    AGE                                                                   NaN
        Under 6 years                                                   31.5%
        6 to 11 years                                                   31.3%
        12 to 17 years                                                  37.2%
...                                                                       ...
41232                                                                     NaN
41159                                                                     NaN
41254                                                                     NaN
41264                                                                     NaN
41180                                                                     NaN

                                      Floyd County, Kentucky!!In married-couple family household!!Estimate  \
Children under 18 years in households                                              4,562
    AGE                                                                              NaN
        Under 6 years                                                              31.3%
        6 to 11 years                                                              26.9%
        12 to 17 years                                                             41.7%
...                                                                                  ...
41232                                                                                NaN
41159                                                                                NaN
41254                                                                                NaN
41264                                                                                NaN
41180                                                                                NaN

                                      Floyd County, Kentucky!!In male householder, no spouse present, family household!!Estimate  \
Children under 18 years in households                                                782
    AGE                                                                              NaN
        Under 6 years                                                              23.7%
        6 to 11 years                                                              47.7%
        12 to 17 years                                                             28.6%
...                                                                                  ...
41232                                                                                NaN
41159                                                                                NaN
41254                                                                                NaN
41264                                                                                NaN
41180                                                                                NaN

                                      Floyd County, Kentucky!!In female householder, no spouse present, family household!!Estimate  \
Children under 18 years in households                                              2,486
    AGE                                                                              NaN
        Under 6 years                                                              32.9%
        6 to 11 years                                                              34.8%
        12 to 17 years                                                             32.3%
...                                                                                  ...
41232                                                                                NaN
41159                                                                                NaN
41254                                                                                NaN
41264                                                                                NaN
41180                                                                                NaN

                                      Greenup County, Kentucky!!Total!!Estimate  \
Children under 18 years in households                                     7,684
    AGE                                                                     NaN
        Under 6 years                                                     30.1%
        6 to 11 years                                                     32.2%
        12 to 17 years                                                    37.6%
...                                                                         ...
41232                                                                       NaN
41159                                                                       NaN
41254                                                                       NaN
41264                                                                       NaN
41180                                                                       NaN

                                      Greenup County, Kentucky!!In married-couple family household!!Estimate  \
Children under 18 years in households                                              5,398
    AGE                                                                              NaN
        Under 6 years                                                              32.8%
        6 to 11 years                                                              33.3%
        12 to 17 years                                                             33.9%
...                                                                                  ...
41232                                                                                NaN
41159                                                                                NaN
41254                                                                                NaN
41264                                                                                NaN
41180                                                                                NaN

                                       ...  \
Children under 18 years in households  ...
    AGE                                ...
        Under 6 years                  ...
        6 to 11 years                  ...
        12 to 17 years                 ...
...                                    ...
41232                                  ...
41159                                  ...
41254                                  ...
41264                                  ...
41180                                  ...

                                      Pike County, Kentucky!!In male householder, no spouse present, family household!!Estimate  \
Children under 18 years in households                                                953
    AGE                                                                              NaN
        Under 6 years                                                              24.3%
        6 to 11 years                                                              33.7%
        12 to 17 years                                                             42.0%
...                                                                                  ...
41232                                                                                NaN
41159                                                                                NaN
41254                                                                                NaN
41264                                                                                NaN
41180                                                                                NaN

                                      Pike County, Kentucky!!In female householder, no spouse present, family household!!Estimate  \
Children under 18 years in households                                              3,042
    AGE                                                                              NaN
        Under 6 years                                                              38.3%
        6 to 11 years                                                              30.6%
        12 to 17 years                                                             31.1%
...                                                                                  ...
41232                                                                                NaN
41159                                                                                NaN
41254                                                                                NaN
41264                                                                                NaN
41180                                                                                NaN

                                      Primary City Population  \
Children under 18 years in households          NaN        NaN
    AGE                                        NaN        NaN
        Under 6 years                          NaN        NaN
        6 to 11 years                          NaN        NaN
        12 to 17 years                         NaN        NaN
...                                            ...        ...
41232                                          NaN        NaN
41159                                          NaN        NaN
41254                                          NaN        NaN
41264                                          NaN        NaN
41180                                          NaN        NaN

                                      Population Under 6    County  \
Children under 18 years in households                NaN       NaN
    AGE                                              NaN       NaN
        Under 6 years                                NaN       NaN
        6 to 11 years                                NaN       NaN
        12 to 17 years                               NaN       NaN
...                                                  ...       ...
41232                                                NaN  Lawrence
41159                                                NaN  Lawrence
41254                                                NaN  Lawrence
41264                                                NaN  Lawrence
41180                                                NaN  Lawrence

                                       Median Home Value  \
Children under 18 years in households                NaN
    AGE                                              NaN
        Under 6 years                                NaN
        6 to 11 years                                NaN
        12 to 17 years                               NaN
...                                                  ...
41232                                                NaN
41159                                                NaN
41254                                                NaN
41264                                                NaN
41180                                                NaN

                                       Median Household Income  \
Children under 18 years in households                      NaN
    AGE                                                    NaN
        Under 6 years                                      NaN
        6 to 11 years                                      NaN
        12 to 17 years                                     NaN
...                                                        ...
41232                                                      NaN
41159                                                      NaN
41254                                                      NaN
41264                                                      NaN
41180                                                      NaN

                                       Type of Internet  \
Children under 18 years in households               NaN
    AGE                                             NaN
        Under 6 years                               NaN
        6 to 11 years                               NaN
        12 to 17 years                              NaN
...                                                 ...
41232                                               NaN
41159                                               NaN
41254                                               NaN
41264                                               NaN
41180                                               NaN

                                      Number of Registered Child Care Providers
Children under 18 years in households                                       NaN
    AGE                                                                     NaN
        Under 6 years                                                       NaN
        6 to 11 years                                                       NaN
        12 to 17 years                                                      NaN
...                                                                         ...
41232                                                                       0.0
41159                                                                       0.0
41254                                                                       0.0
41264                                                                       0.0
41180                                                                       0.0

[328 rows x 24 columns]

Hm. Well that's interesting.